import type { EtsyPromptTemplate, EtsyImageType } from "./types.js";

export const ETSY_PROMPT_TEMPLATES: EtsyPromptTemplate[] = [
  {
    templateId: "etsy-product-fidelity",
    name: "Etsy 商品保真参考图",
    description: "默认商品图生图模板：同一商品，不换款，不改色，不添加额外商品。",
    category: "main",
    basePrompt: "Product fidelity Etsy listing image based on the input reference photo: same exact product, improved background, lighting, crop, and composition only.",
    recommendedAngles: ["front centered", "45-degree product view", "detail close-up", "clean lifestyle crop", "material macro", "thumbnail-safe square crop"],
    negativePrompt: "no new product design, no changed product category, no changed main color, no extra product, no changed material, no fake logo, no invented text, no people, no hands, no feet, no model unless explicitly requested",
    aspectRatio: "1:1",
    creativeStrength: "low",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-white-main",
    name: "Etsy 白底主图",
    description: "干净、缩略图友好、主体居中，适合 listing 第一张图。",
    category: "main",
    basePrompt: "Clean Etsy listing hero image on a warm white or very light neutral background, centered product, truthful product appearance, soft studio light.",
    recommendedAngles: ["front centered", "slight 45-degree front angle"],
    negativePrompt: "no fake logo, no watermark, no text gibberish, no extra accessories, no changed material, no changed color, no unrealistic scale",
    aspectRatio: "1:1",
    creativeStrength: "low",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-premium-main",
    name: "Etsy 高级感产品主图",
    description: "更精致的光线与背景，但保持商品真实可信。",
    category: "main",
    basePrompt: "Premium Etsy product photography with restrained styling, soft directional light, subtle surface texture, product remains accurate and recognizable.",
    recommendedAngles: ["front centered", "45-degree hero view", "top-down clean composition"],
    negativePrompt: "no luxury brand imitation, no invented packaging, no fake certification mark, no changed product shape",
    aspectRatio: "1:1",
    creativeStrength: "medium",
    etsyComplianceLevel: "balanced",
  },
  {
    templateId: "etsy-angle-set",
    name: "Etsy 多角度展示图",
    description: "为同一商品生成正面、侧面、背面、俯视等差异化角度。",
    category: "angle",
    basePrompt: "Accurate multi-angle Etsy listing product photo, consistent product identity, clear edges and silhouette, neutral background.",
    recommendedAngles: ["front view", "side view", "back view", "45-degree angle", "top-down view"],
    negativePrompt: "no product deformation, no missing parts, no extra features, no changed dimensions",
    aspectRatio: "1:1",
    creativeStrength: "low",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-detail-craft",
    name: "Etsy 细节展示图",
    description: "强调材质、纹理、手工痕迹和边缘细节。",
    category: "detail",
    basePrompt: "Close-up Etsy detail shot showing material texture, craftsmanship, edges, finish, and truthful imperfections where present.",
    recommendedAngles: ["macro detail", "texture close-up", "edge detail", "finish detail"],
    negativePrompt: "no artificial engraving unless present, no fake handmade marks, no invented stones or parts",
    aspectRatio: "1:1",
    creativeStrength: "medium",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-handmade-texture",
    name: "Etsy 手工质感",
    description: "突出真实手工痕迹、纹理和自然光，不把普通商品伪装成不存在的 handmade。",
    category: "detail",
    basePrompt: "Truthful handmade-feel Etsy product photography emphasizing visible craft texture, natural imperfections, tactile surface, and warm but accurate light.",
    recommendedAngles: ["soft front view", "craft texture close-up", "edge and finish detail", "hands-near-product scale context"],
    negativePrompt: "no fake handmade claim, no invented engraving, no added tools, no changed material, no extra accessories",
    aspectRatio: "1:1",
    creativeStrength: "medium",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-size-detail",
    name: "Etsy 尺寸细节图",
    description: "展示比例和尺寸感，不误导买家以为道具随商品附赠。",
    category: "scale",
    basePrompt: "Etsy scale and size detail image with a neutral everyday comparison context, product remains accurate, no implied included props.",
    recommendedAngles: ["top-down scale context", "side profile showing thickness", "hand scale context", "edge measurement-style composition without readable numbers"],
    negativePrompt: "no fake measurement text, no misleading size, no included prop implication, no altered dimensions",
    aspectRatio: "1:1",
    creativeStrength: "low",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-material-detail",
    name: "Etsy 材质细节图",
    description: "强调真实材质纹理、反光、织物、木纹、金属或表面工艺。",
    category: "detail",
    basePrompt: "Etsy material detail product photography showing accurate surface texture, finish, reflection, weave, grain, metal, ceramic, wood, fabric, or other visible material cues.",
    recommendedAngles: ["macro material detail", "surface reflection angle", "edge finish close-up", "texture flat lay detail"],
    negativePrompt: "no changed material, no fake gemstone, no false premium finish, no artificial defects unless visible",
    aspectRatio: "1:1",
    creativeStrength: "medium",
    etsyComplianceLevel: "strict",
  },
  {
    templateId: "etsy-gift-lifestyle",
    name: "Etsy 礼品场景图",
    description: "合理礼品场景，不虚构包装或配件。",
    category: "lifestyle",
    basePrompt: "Etsy lifestyle product photo in a tasteful gift context, cozy but not misleading, product remains the clear focus.",
    recommendedAngles: ["gift table scene", "in-use context", "soft seasonal surface"],
    negativePrompt: "no fake branded packaging, no included accessories unless visible in references, no misleading bundle",
    aspectRatio: "1:1",
    creativeStrength: "medium",
    etsyComplianceLevel: "balanced",
  },
  {
    templateId: "etsy-seasonal-creative",
    name: "Etsy 节日风格图",
    description: "节日氛围和背景创意，但不改变商品本体。",
    category: "creative",
    basePrompt: "Creative seasonal Etsy listing image with tasteful background atmosphere, accurate product body, no misleading claims or props.",
    recommendedAngles: ["seasonal hero", "creative flat lay", "warm lifestyle angle"],
    negativePrompt: "no false brand, no changed material, no implied function not present, no misleading size",
    aspectRatio: "1:1",
    creativeStrength: "high",
    etsyComplianceLevel: "creative_safe",
  },
];

export function getTemplate(templateId?: string): EtsyPromptTemplate {
  return ETSY_PROMPT_TEMPLATES.find((t) => t.templateId === templateId) ?? ETSY_PROMPT_TEMPLATES[0]!;
}

export function imageTypeForIndex(index: number): EtsyImageType {
  const order: EtsyImageType[] = ["main", "angle", "detail", "scale", "lifestyle", "creative"];
  return order[index % order.length]!;
}
